/*
 * Copyright (c) 2012, TATRC and Tribal
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 * * Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 * * Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in the
 *   documentation and/or other materials provided with the distribution.
 * * Neither the name of TATRC or TRIBAL nor the
 *   names of its contributors may be used to endorse or promote products
 *   derived from this software without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL TATRC OR TRIBAL BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

package com.tribal.omlet.download;

import java.io.Serializable;

import com.tribal.mobile.api.packages.PackageItem;

/**
 * Class that represents a download notification status result.
 * 
 * @author Jon Brasted
 */
public class DownloadNotificationStatusResult implements Serializable {

	/**
	 * Autogenerated serial version UID 
	 */
	private static final long serialVersionUID = -1819290126919159975L;

	/* Fields */

	private int notificationId;
	private PackageItem packageItem;
	private DownloadNotificationStatus notificationStatus;
	
	private String statusText;
	private int progress;
	private int max;
	
	/* Properties */	
	
	public int getNotificationId() {
		return notificationId;
	}
	
	public void setNotificationId(int notificationId) {
		this.notificationId = notificationId;
	}
	
	public PackageItem getPackageItem() {
		return packageItem;
	}
	
	public void setPackageItem(PackageItem packageItem) {
		this.packageItem = packageItem;
	}
	
	public DownloadNotificationStatus getNotificationStatus() {
		return notificationStatus;
	}
	
	public void setNotificationStatus(DownloadNotificationStatus notificationStatus) {
		this.notificationStatus = notificationStatus;
	}
	
	public String getStatusText() {
		return statusText;
	}

	public void setStatusText(String statusText) {
		this.statusText = statusText;
	}

	public int getProgress() {
		return progress;
	}

	public void setProgress(int progress) {
		this.progress = progress;
	}

	public int getMax() {
		return max;
	}

	public void setMax(int max) {
		this.max = max;
	}
	
	/* Constructor */
	
	public DownloadNotificationStatusResult(int notificationId, PackageItem packageItem, DownloadNotificationStatus notificationStatus) {
		this.notificationId = notificationId;
		this.packageItem = packageItem;
		this.notificationStatus = notificationStatus;
	}
	
	public DownloadNotificationStatusResult(int notificationId, PackageItem packageItem, DownloadNotificationStatus notificationStatus, String statusText, int progress, int max) {
		this(notificationId, packageItem, notificationStatus);
		this.statusText = statusText;
		this.progress = progress;
		this.max = max;
	}
}
